
development:
  adapter: postgresql
  encoding: unicode
  database: hermes_web_development


test:
  adapter: postgresql
  encoding: unicode
  database: hermes_web_test

production:
  adapter: postgresql
  encoding: unicode
  database: hermes_web_production

 